name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    strategy:
      matrix:
        Configuration: [Debug, Release]

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Setup .NET Core 2.1
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.1

    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore --configuration ${{ matrix.Configuration }}
      
    - name: Test
      run: dotnet test --no-build --verbosity normal --configuration ${{ matrix.Configuration }}

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v2.3.1
      with:
        name: ${{ matrix.Configuration }}
        path: .\src\AzurePipelines.TestLogger\bin\${{ matrix.Configuration }}\netstandard1.5\*.*
        if-no-files-found: error

    - name: Add Semver.dll to Build Artifacts
      uses: actions/upload-artifact@v2.3.1
      with:
        name: ${{ matrix.Configuration }}
        path: ~\.nuget\packages\semver\2.0.6\lib\netstandard1.1\*.*
        if-no-files-found: error

    - name: Add documentation to Build Artifacts
      uses: actions/upload-artifact@v2.3.1
      with:
        name: ${{ matrix.Configuration }}
        path: |
          .\LICENSE
          .\README.md
          .\ReleaseNotes.md
        if-no-files-found: error